--- #YAML:1.0
name:                Geo-OSM-MapFeatures
version:             0.02
abstract:            Parses and represents OpenStreetMap Map Features
license:             ~
author:              
    - Knut Arne Bjørndal <bob+osm@cakebox.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Error:                         0
    LWP::UserAgent:                0
    Storable:                      0
    Test::More:                    0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
